# Generated by Django 4.0.7 on 2023-02-12 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of vote'),
            preserve_default=False,
        ),
    ]
